[general]
RemoteNickFormat="{NICK} ({CHANNEL}@{LABEL}): "
TranslationAttribution=" [translated by :google:]"
PreserveThreading=true
ShowUserTyping=true
MediaDownloadSize=1000000
ShowJoinPart=true
# When someone is speaking from a platform without avatars, generate one from usernames
IconURL="https://github.com/identicons/{NICK}.png"

## ACCOUNTS

[slack.codeforall]
Label="Code for All"

[slack.epanstwo]
Label="ePanstwo (Poland)"

[slack.cfjapan]
Label="Code for Japan"

[slack.g0vtw]
Label="g0v"


## GATEWAYS & BRIDGES

[[gateway]]
name="cfall-general"
enable=true

  [[gateway.inout]]
  account="slack.epanstwo"
  channel="mbtest"
  
  [[gateway.inout]]
  account="slack.cfall"
  channel="mbtest"
  
  [[gateway.inout]]
  account="slack.cfall"
  channel="mbtest-en"
  [gateway.inout.options]
    locale="en"
